test:
	perl -I ../.. -cw Abstract.pm
	perl -I ../.. -cw Application.pm
	perl -I ../.. -cw Browser.pm
	perl -I ../.. -cw CommandHandler.pm
	perl -I ../.. -cw Config.pm
	perl -I ../.. -cw Directory.pm
	perl -I ../.. -cw File.pm
	perl -I ../.. -cw History.pm
	perl -I ../.. -cw JobHandler.pm
	perl -I ../.. -cw Screen.pm
	perl -I ../.. -cw State.pm
	perl -I ../.. -cw Util.pm
	perl -I ../.. -cw pfm-2
	make -C Job test
	make -C Screen test
