test:
	perl -I ../../.. -cw Abstract.pm
	perl -I ../../.. -cw Bazaar.pm
	perl -I ../../.. -cw CheckUpdates.pm
	perl -I ../../.. -cw Cvs.pm
	perl -I ../../.. -cw Git.pm
	perl -I ../../.. -cw RCS.pm
	perl -I ../../.. -cw Subversion.pm
