#!/bin/sh

# expects:
# $0      $1 $2     $3 $4      $5 $6     $7     $8
# install -o <user> -g <group> -m <mode> <file> <installdir>

if [ "x$1" = x-c ] then
	shift
fi

# -o
user="$2"
# -g
group="$4"
# -m
mode="$6"
file="$7"
dir="$8"

cp "$file" "$dir"
chmod "$mode" "$dir/$file"
chown "$user:$group" "$dir/$file"


